class apiUrl {
    serviceApi = "https://dev.infoaugust.com/api"   
    domainUrl = "https://dev.infoaugust.com/"
    baseUrl = "https://dev.infoaugust.com/"    
    uploadedDoc = "/uploadedDoc"
    common = "/common"
    partner = "/partner"
    cron = "/cron"
    logo = '/logo' 
    sendMail = "/sendMail"
    uploadPartner = "/uploadPartner" 

    processLedgerSummary = "/processLedgerSummary"
    processMonthlyTransaction = "/processMonthlyTransaction"
    processCreditNoteSummary = "/processCreditNoteSummary"
    processInvoiceSummary = "/processInvoiceSummary"
    processCreditNoteWorking = "/processWorkingFile"  
    uploadPartnerFromSftp = "/uploadPartnerFromSftp"
    copyPartnerFileFromSftp = "/copyPartnerFileFromSftp"
    copyCreditNoteSummaryFileFromSftp = "/copyCreditNoteSummaryFileFromSftp"
    copyCreditNoteWorkingFileFromSftp = "/copyCreditNoteWorkingFileFromSftp"
    copyCreditNotePdfFileFromSftp = "/copyCreditNotePdfFileFromSftp"
    copyLedgerSummaryFileFromSftp = "/copyLedgerSummaryFileFromSftp"
    copyInvoiceSummaryFileFromSftp = "/copyInvoiceSummaryFileFromSftp"
    copyInvoicePdfFileFromSftp = "/copyInvoicePdfFileFromSftp"
    copyMonthlyTransactionFileFromSftp = "/copyMonthlyTransactionFileFromSftp"
    getCreditNoteSummaryFileFromInputFolder = "/getCreditNoteSummaryFileFromInputFolder"
    getCreditNoteWorkingFileFromInputFolder = "/getCreditNoteWorkingFileFromInputFolder"
    getPartnerFileFromInputFolder = "/getPartnerFileFromInputFolder"
    getLedgerSummaryFileFromInputFolder = "/getLedgerSummaryFileFromInputFolder"
    getInvoiceSummaryFileFromInputFolder = "/getInvoiceSummaryFileFromInputFolder"
    getMonthlyTransactionFileFromInputFolder = "/getMonthlyTransactionFileFromInputFolder"

    processLedgerSummaryLocal = "/processLedgerSummaryLocal"
    processMonthlyTransactionLocal = "/processMonthlyTransactionLocal"
    processCreditNoteSummaryLocal = "/processCreditNoteSummaryLocal"
    processInvoiceSummaryLocal = "/processInvoiceSummaryLocal"
    processInvoicePtLocal = "/processInvoicePtLocal"
    processCreditNoteWorkingLocal = "/processWorkingFileLocal"  
    uploadPartnerFromSftpToLocal = "/uploadPartnerFromSftpToLocal"
    
    copyPartnerFileFromSftpToLocal = "/copyPartnerFileFromSftpToLocal"
    copyCreditNoteSummaryFileFromSftpToLocal = "/copyCreditNoteSummaryFileFromSftpToLocal"
    copyCreditNoteWorkingFileFromSftpToLocal = "/copyCreditNoteWorkingFileFromSftpToLocal"
    copyCreditNotePdfFileFromSftpToLocal = "/copyCreditNotePdfFileFromSftpToLocal"
    copyLedgerSummaryFileFromSftpToLocal = "/copyLedgerSummaryFileFromSftpToLocal"
    copyInvoiceSummaryFileFromSftpToLocal = "/copyInvoiceSummaryFileFromSftpToLocal"
    copyInvoicePdfFileFromSftpToLocal = "/copyInvoicePdfFileFromSftpToLocal"
    copyMonthlyTransactionFileFromSftpToLocal = "/copyMonthlyTransactionFileFromSftpToLocal"
    copyInvoicePtFileFromSftpToLocal = "/copyInvoicePtFileFromSftpToLocal"
    getCreditNoteSummaryFileFromInputFolderLocal = "/getCreditNoteSummaryFileFromInputFolderLocal"
    getCreditNoteWorkingFileFromInputFolderLocal = "/getCreditNoteWorkingFileFromInputFolderLocal"
    getPartnerFileFromInputFolderLocal = "/getPartnerFileFromInputFolderLocal"
    getLedgerSummaryFileFromInputFolderLocal = "/getLedgerSummaryFileFromInputFolderLocal"
    getInvoiceSummaryFileFromInputFolderLocal = "/getInvoiceSummaryFileFromInputFolderLocal"
    getMonthlyTransactionFileFromInputFolderLocal = "/getMonthlyTransactionFileFromInputFolderLocal"
    getInvoicePtFileFromInputFolderLocal = "/getInvoicePtFileFromInputFolderLocal"
        
}

module.exports = apiUrl;